name: todo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: 
  get: 
  intl: 
  date_picker_timeline: ^1.2.6 
  sqflite: 
  flutter_staggered_animations: 
  flutter_svg: 
  rxdart: 
  google_fonts: ^6.2.0
  flutter_local_notifications: ^17.2.1+2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: 
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/appicon.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true

  assets:
    - images/person.jpeg
    - images/task.svg
